name: maven_build_and-deploy

on: workflow_dispatch

jobs:
    SSH-to-azureVM:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}

      - name: Deploy Docker container to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << EOF
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin
          
          sudo docker build -t japp:v1 .
          sudo docker tag japp:v1 lakulos/nodeapprepo:mavenimg
          sudo docker push lakulos/nodeapprepo:mavenimg
          sudo docker pull lakulos/nodeapprepo:mavenimg
          sudo docker run -d --name maven-container -p 8080:8080 lakulos/nodeapprepo:mavenimg

          docker image prune -f
          EOF
